In [2]:
import random
import numpy as np

In [3]:
x = np.random.randint(1,100,(3,3))
x

array([[51, 17, 94],
       [72, 11, 33],
       [ 8, 75, 75]])

In [4]:
x.shape

(3, 3)

In [5]:
a = x[2::2]
a

array([[ 8, 75, 75]])

In [6]:
x = x.reshape(-1)
x

array([51, 17, 94, 72, 11, 33,  8, 75, 75])

In [7]:
a = x[2::2]
a

array([94, 11,  8, 75])

In [8]:
print(x.shape)
x.dtype

(9,)


dtype('int32')

In [9]:
a = np.random.randint(1,100,(3,3))
x = np.copy(a)


In [10]:
np.concatenate((a,x))

array([[84, 86, 34],
       [39, 28, 25],
       [ 5, 92, 55],
       [84, 86, 34],
       [39, 28, 25],
       [ 5, 92, 55]])

In [11]:
np.vstack((x, a))

array([[84, 86, 34],
       [39, 28, 25],
       [ 5, 92, 55],
       [84, 86, 34],
       [39, 28, 25],
       [ 5, 92, 55]])

In [12]:
np.concatenate((x,a), axis = 1)

array([[84, 86, 34, 84, 86, 34],
       [39, 28, 25, 39, 28, 25],
       [ 5, 92, 55,  5, 92, 55]])

In [13]:
np.concatenate((x,a), axis = None)

array([84, 86, 34, 39, 28, 25,  5, 92, 55, 84, 86, 34, 39, 28, 25,  5, 92,
       55])

In [14]:
a = np.arange(26)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [15]:
newarr = np.array_split(a, 4)
newarr

[array([0, 1, 2, 3, 4, 5, 6]),
 array([ 7,  8,  9, 10, 11, 12, 13]),
 array([14, 15, 16, 17, 18, 19]),
 array([20, 21, 22, 23, 24, 25])]

In [38]:
x = np.random.random((100,500))
y = np.random.random((1000,500))
temp = np.sum(np.square(y), axis=1)
print(temp.shape)
print(y.shape)
count = np.transpose([np.sum(np.square(y), axis=1)])
print(count.shape)
print(count+temp)


(1000,)
(1000, 500)
(1000, 1)
[[329.07408419 332.47591965 336.68664442 ... 328.72678728 329.68557852
  325.61503936]
 [332.47591965 335.87775512 340.08847988 ... 332.12862275 333.08741399
  329.01687483]
 [336.68664442 340.08847988 344.29920464 ... 336.33934751 337.29813875
  333.22759959]
 ...
 [328.72678728 332.12862275 336.33934751 ... 328.37949038 329.33828162
  325.26774246]
 [329.68557852 333.08741399 337.29813875 ... 329.33828162 330.29707286
  326.2265337 ]
 [325.61503936 329.01687483 333.22759959 ... 325.26774246 326.2265337
  322.15599453]]
