In [1]:
import numpy as np

# Ex1

Tạo mảng 1 chiều x gồm n số thực

In [2]:
n = 10
x = np.array([x for x in range(n)], dtype=float)

In [3]:
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

Chọn 3 hàm số tuỳ ý $f_1(x)$, $f_2(x)$, $f_3(x)$. Tạo 3 mảng bằng cách truyền $x$ vào trong 3 hàm số

In [4]:
def f1(a):
    return a**2
def f2(a):
    return np.sin(a)
def f3(a):
    return 2**a

print("F1(x) = ", f1(x))
print("F2(x) = ", f2(x))
print("F3(x) = ", f3(x))

F1(x) =  [ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]
F2(x) =  [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
F3(x) =  [  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]


Ghép bốn mảng một chiều thành một mảng hai chiều kích thước $n\times4$

In [5]:
arr1 = np.array([1,2,3,4,1,3])
arr2 = np.array([2,3,4,2,6,7])
arr3 = np.array([5,6,7,23,7,2])
arr4 = np.array([123,4,1,3,0,3])

In [6]:
arr = np.concatenate([np.vstack([arr1, arr2]), np.vstack([arr3,arr4])])
print(arr)

[[  1   2   3   4   1   3]
 [  2   3   4   2   6   7]
 [  5   6   7  23   7   2]
 [123   4   1   3   0   3]]


# Ex2

In [7]:
import numpy as np

Tải dữ liệu file `heart_rate.txt` vào trong mảng `a`

In [8]:
a = np.genfromtxt("heart_rate.txt", delimiter=",", skip_header=True)
a

array([[   0.,  103.],
       [   5.,  103.],
       [  10.,  103.],
       [  15.,  105.],
       [  20.,  108.],
       [  25.,  110.],
       [  30.,  110.],
       [  35.,  112.],
       [  40.,  112.],
       [  45.,  114.],
       [  50.,  114.],
       [  55.,  117.],
       [  60.,  117.],
       [  65.,  118.],
       [  70.,  119.],
       [  75.,  119.],
       [  80.,  120.],
       [  85.,  121.],
       [  90.,  121.],
       [  95.,  122.],
       [ 100.,  123.],
       [ 105.,  124.],
       [ 110.,  124.],
       [ 115.,  125.],
       [ 120.,  126.],
       [ 125.,  127.],
       [ 130.,  128.],
       [ 135.,  127.],
       [ 140.,  128.],
       [ 145.,  128.],
       [ 150.,  129.],
       [ 155.,  129.],
       [ 160.,  130.],
       [ 165.,  131.],
       [ 170.,  132.],
       [ 175.,  132.],
       [ 180.,  132.],
       [ 185.,  133.],
       [ 190.,  134.],
       [ 195.,  135.],
       [ 200.,  135.],
       [ 205.,  135.],
       [ 210.,  135.],
       [ 21

In [9]:
Time = a[:, 0]
Heart_rate = a[:, 1]

Thực hiện mô tả thống kê với các biến `Time` và `Heart Rate`: Cỡ mẫu, trung bình, trung vị, độ lệch chuẩn, giá trị lớn nhất, nhỏ nhất, phần tư Q1, Q2 và Q3


In [10]:
print(len(Time))
print(len(Heart_rate))

241
241


The mean

In [11]:
Ave_Time = np.sum(Time)/len(Time) # Or Ave_Time = np.mean(Time)
print(Ave_Time)
Ave_Heart = np.sum(Heart_rate)/len(Heart_rate) # Or Ave_Heart = np.mean(Heart_rate)
print(Ave_Heart)

600.0
142.98340248962654


The median

In [22]:
median_Time = np.median(Time)
print(median_Time)
median_Heart = np.median(Heart_rate)
print(median_Heart)

600.0
147.0


Standard deviation

In [25]:
std_time = np.std(Time)
print(std_time)
std_heart = np.std(Heart_rate)
print(std_heart)

347.85054261852173
11.36346581057221


Max and min

In [38]:
print("Max Time:", max(Time), "Min Time:", min(Time))
print("Max rate:", max(Heart_rate), "Min Rate:", min(Heart_rate))

Max Time: 1200.0 Min Time: 0.0
Max rate: 154.0 Min Rate: 103.0


The first quartile (Q1), second quartile (Q2), and third quartile (Q3)


In [40]:

Q1 = np.percentile(Heart_rate, 25)
Q2 = np.percentile(Heart_rate, 50)
Q3 = np.percentile(Heart_rate, 75)
Q4 = np.percentile(Time, 25)
Q5 = np.percentile(Time, 50)
Q6 = np.percentile(Time, 75)

print("Q1:", Q1)
print("Q2:", Q2)
print("Q3:", Q3)
print("Q1:", Q4)
print("Q2:", Q5)
print("Q3:", Q6)

Q1: 138.0
Q2: 147.0
Q3: 151.0
Q1: 300.0
Q2: 600.0
Q3: 900.0
