In [3]:
import random
import numpy as np

In [13]:
x = np.random.randint(1,100,(3,3))
x

array([[93,  7, 94],
       [84, 73, 14],
       [17, 22, 34]])

In [29]:
x.shape

(9,)

In [40]:
a = x[2::2]
a

array([94, 73, 17, 34])

In [15]:
x = x.reshape(-1)
x

array([93,  7, 94, 84, 73, 14, 17, 22, 34])

In [21]:
a = x[2::2]
a

array([94, 73, 17, 34])

In [54]:
print(x.shape)
x.dtype

(3, 3)


dtype('int32')

In [46]:
a = np.random.randint(1,100,(3,3))
x = np.copy(a)


In [48]:
np.concatenate((a,x))

array([[50, 86, 69],
       [68, 84, 37],
       [33, 42,  2],
       [50, 86, 69],
       [68, 84, 37],
       [33, 42,  2]])

In [49]:
np.vstack((x, a))

array([[50, 86, 69],
       [68, 84, 37],
       [33, 42,  2],
       [50, 86, 69],
       [68, 84, 37],
       [33, 42,  2]])

In [52]:
np.concatenate((x,a), axis = 1)

array([[50, 86, 69, 50, 86, 69],
       [68, 84, 37, 68, 84, 37],
       [33, 42,  2, 33, 42,  2]])

In [53]:
np.concatenate((x,a), axis = None)

array([50, 86, 69, 68, 84, 37, 33, 42,  2, 50, 86, 69, 68, 84, 37, 33, 42,
        2])

In [58]:
a = np.arange(26)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [66]:
newarr = np.array_split(a, 4)
newarr

[array([0, 1, 2, 3, 4, 5, 6]),
 array([ 7,  8,  9, 10, 11, 12, 13]),
 array([14, 15, 16, 17, 18, 19]),
 array([20, 21, 22, 23, 24, 25])]